-- Migration 0001: per-pillar action plans
-- Context: the app bootstraps schema with SQLAlchemy `create_all`, which does NOT
-- alter existing tables. Run this script ONCE against an existing MySQL database to
-- bring `goal_actions` / `goal_breakdowns` in line with the per-pillar action-plan model.
--
-- Changes:
--   1. goal_breakdowns.status gains the 'failed' value (used by deadline sync).
--   2. goal_actions moves from one-plan-per-goal (UNIQUE goal_id) to one-plan-per
--      main breakdown node: adds main_breakdown_id (FK), drops the goal_id unique
--      constraint, and adds a composite UNIQUE (goal_id, main_breakdown_id).
--
-- NOTE: existing action plans cannot be mapped to a main breakdown node, so they are
-- dropped and will be regenerated by the AI pipeline. Run inside a maintenance window.

USE ai_mentor_db;

-- 1) Allow 'failed' on breakdown nodes
ALTER TABLE goal_breakdowns
    MODIFY COLUMN status ENUM('pending', 'in_progress', 'completed', 'failed') NOT NULL DEFAULT 'pending';

-- 2) Recreate action-plan tables under the per-pillar model.
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS goal_action_items;
DROP TABLE IF EXISTS goal_actions;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE goal_actions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    goal_id INT UNSIGNED NOT NULL,
    main_breakdown_id INT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT NULL,
    status ENUM('pending', 'in_progress', 'completed', 'archived', 'failed') NOT NULL DEFAULT 'pending',
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_goal_actions_goal FOREIGN KEY (goal_id) REFERENCES user_goals (id) ON DELETE CASCADE,
    CONSTRAINT fk_goal_actions_main_breakdown FOREIGN KEY (main_breakdown_id) REFERENCES goal_breakdowns (id) ON DELETE CASCADE,
    CONSTRAINT uq_action_plan_goal_main_breakdown UNIQUE (goal_id, main_breakdown_id),
    INDEX idx_goal_actions_goal (goal_id),
    INDEX idx_goal_actions_main_breakdown (main_breakdown_id),
    INDEX idx_goal_actions_status (status)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE goal_action_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    plan_id INT UNSIGNED NOT NULL,
    breakdown_id INT UNSIGNED NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    frequency ENUM('once', 'daily', 'weekly', 'monthly', 'custom') NOT NULL DEFAULT 'custom',
    schedule TEXT NULL,
    status ENUM('pending', 'in_progress', 'completed', 'archived', 'failed') NOT NULL DEFAULT 'pending',
    start_date DATE NULL,
    due_date DATE NULL,
    sequence SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_goal_action_items_plan FOREIGN KEY (plan_id) REFERENCES goal_actions (id) ON DELETE CASCADE,
    CONSTRAINT fk_goal_action_items_breakdown FOREIGN KEY (breakdown_id) REFERENCES goal_breakdowns (id) ON DELETE SET NULL,
    INDEX idx_goal_action_items_plan (plan_id),
    INDEX idx_goal_action_items_breakdown (breakdown_id),
    INDEX idx_goal_action_items_status (status),
    INDEX idx_goal_action_items_sequence (sequence)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
